### ISSUE TITLE
how does one use it?

### ISSUE THREAD

**Issue by RedNo7** [malisipi/FireSSB#10]
I've installed the extension but there are no instructions to use it and I have searched in every menu.
Can you please advise how to create an SSB app with this?

Thanks!

**Comment by malisipi** [comment]
You can use the guide that placed on FireSSB interface.

1. Open FireSSB popup firstly. Click extension button and click FireSSB section.
![resim](https://github.com/user-attachments/assets/85fa5e2d-6755-4750-95e6-0ba77d27d1bf)

2. You can click highlighted button to open guide. (Somethings would be missing in guide, you can ask any question about FireSSB by GitHub.)
![resim](https://github.com/user-attachments/assets/63552ecf-dc46-4c88-8200-07d96a77bbe3)

However I will introduce basicly. After opening FireSSB popup (via first step placed above). It will ask you a URL and Name. You can fill from current tab via pressing first icon button. And you can copy the generated link from clicking second icon button (that has copy icon). After copied the URL; you can create a desktop shortcut, you can create a bookmark that opens the website in SSB mode.

**Comment by RedNo7** [comment]
thank you!
