### ISSUE TITLE
Only 1 SSB per Profile can be launched

### ISSUE THREAD

**Issue by tijptjik** [malisipi/FireSSB#2]
![image](https://github.com/malisipi/FireSSB/assets/645283/601c0d33-8f4d-4193-884b-bd9aae71f96f)

### Issue

When attempting to launch an SSB through the FireSSB extension from the desktop, it provides the above error message. It runs as expected when no other Firefox windows are open, or if a different profile is selected to launch the SSB in. However, launching a second SSB in that same profile would trigger the same issue, so currently a different profile would be required for each SSB, whereas we would want to run multiple SSBs in the default profile alongside each other.

### System

![image](https://github.com/malisipi/FireSSB/assets/645283/faf38e7f-53ea-4dd5-bfc0-c8f5f30651e1)

### Desktop Entry

```ini
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Terminal=false
Exec=firefox -P firessb 'moz-extension://9747a147-d331-4e20-bdad-b51da3606593/ssb.html?url=https=-=3A=-=2F=-=2Fchat.openai.com=-=2F&name=ChatGPT&incognito=false'
Name=GPT
Icon=applications-internet
```

**Comment by malisipi** [comment]
Normally multiple SSB windows can be opened with same profile and same time.

The error is popups when Firefox was started with [`-new-instance`](https://wiki.mozilla.org/Firefox/CommandLineOptions#-new-instance) or [`-no-remote`](https://wiki.mozilla.org/Firefox/CommandLineOptions#-no-remote) flag. It could be default config of Fedora. I will check the configuration of Fedora package.

Also can you try to add [`-new-tab`](https://wiki.mozilla.org/Firefox/CommandLineOptions#-new-tab_URL) or [`-new-window`](https://wiki.mozilla.org/Firefox/CommandLineOptions#-new-window_URL) flag. It maybe solve the issue.

**Comment by tijptjik** [comment]
Just to provide more detail on how it behaves 'in the wild' :

- When I create one `.desktop` (service A) file like

```ini
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Terminal=false
Exec=firefox 'moz-extension://73d87f2a-55f8-4959-a71e-12523705e04d/ssb.html?url=https=-=3A=-=2F=-=2Fhongkongfp.com=-=2F&name=Hong=-=20Kong=-=20Free=-=20Press=-=20HKFP=-=3A=-=20Independent=-=2C=-=20impartial=-=20news&incognito=false'
Name=HKFP
Icon=applications-internet
```
and copy paste it into another `.desktop` but chance the `url=` parameter (service B), if I first launch service A, it opens just fine, opening service B however _replaces_ the window in which service A was running instead of spawning a new one.

This behaviour can be remedied by adding `-new-window` to the launch command like you said, i.e.:

```Exec=firefox -new-window 'moz-extension://73d87f2a-55f8-4959-a71e-12523705e04d/ssb.html?url=https=-=3A=-=2F=-=2Fhongkongfp.com=-=2F&name=Hong=-=20Kong=-=20Free=-=20Press=-=20HKFP=-=3A=-=20Independent=-=2C=-=20impartial=-=20news&incognito=false'```

However, while `-new-tab` the issue isn't resolved and replacement still happens, with the added annoyance that a new helper tab is opened in Firefox proper:

![image](https://github.com/malisipi/FireSSB/assets/645283/16f4bf1e-65db-4b1d-ad23-089d9677834e)

The `-new-window` window flag doesn't suffer from this issue, so TL;DR it is a necessary flag to trigger the expected behaviour :) 

Perhaps just updating the docs to make mention of this would be sufficient to consider this issue closed :)
